import { useState } from 'react'

const workflows = [
  {
    file: 'docker-build-push.yml',
    title: '🐳 Docker Build & Push',
    desc: 'Takes your code, puts it in a container, and sends it to GitHub & Docker Hub.',
    demo: '1. Create a tag starting with "v" (e.g. v1.0.0). 2. Watch it build for both Intel and Mac chips. 3. Check your GitHub Packages page for the result.',
    tags: ['Multi-arch', 'Scanner']
  },
  {
    file: 'ci-advanced.yml',
    title: '🧪 Advanced CI',
    desc: 'The "Everything Check". Runs tests on multiple versions of Node.js and talks to AWS without storing passwords.',
    demo: '1. Go to Actions → "Advanced CI Pipeline". 2. Click "Run workflow". 3. Observe the "Matrix" splitting the work into multiple parallel jobs.',
    tags: ['OIDC', 'Dynamic Matrix']
  },
  {
    file: 'release-automation.yml',
    title: '🚀 Auto-Release',
    desc: 'The "Robot Librarian". Automatically writes changelogs and decides if we need a new version number.',
    demo: '1. Push a commit starting with "feat:" or "fix:". 2. Observe as a new GitHub Release is created automatically with professional notes.',
    tags: ['Semantic', 'Changelog']
  },
  {
    file: 'pr-automation.yml',
    title: '🤖 PR Assistant',
    desc: 'The "Code Review Buddy". Keeps Pull Requests clean by labeling them and checking titles.',
    demo: '1. Open a new Pull Request. 2. Notice the "Size" label (XS/S/M/L) and the automated checklist comment that appears.',
    tags: ['Labels', 'Checklist']
  },
  {
    file: 'security-scan.yml',
    title: '🛡️ Security Guard',
    desc: 'Scans your code for leaks, bugs, and dangerous dependencies before they hit production.',
    demo: '1. Go to Github → Security → Code scanning. 2. See the detailed vulnerability report generated by this workflow.',
    tags: ['CodeQL', 'Secrets']
  },
  {
    file: 'scheduled-tasks.yml',
    title: '⏰ Scheduled Jobs',
    desc: 'Your "Team Maintenance" script. Runs every morning to clean up old issues and check certificate dates.',
    demo: '1. Run this manually via "workflow_dispatch". 2. Go to Issues and see if a new "Weekly Report" was posted by the robot.',
    tags: ['Cron', 'Reporting']
  }
]

export default function SlideYAMLGuide() {
  const [active, setActive] = useState(0)
  const current = workflows[active]

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column', gap: 12 }}>
      <div>
        <div className="tag tag-green fade-up delay-1" style={{ marginBottom: 8 }}>04 — Presenter's Guide</div>
        <h2 className="section-title fade-up delay-2">Workflow Demos: How to Present</h2>
        <p className="section-subtitle fade-up delay-3">Simple descriptions and instructions for live testing the YAML files</p>
      </div>

      <div className="grid-2 fade-up delay-2" style={{ gap: 16, flex: 1, overflow: 'hidden' }}>
        {/* List */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 6, overflowY: 'auto' }}>
          {workflows.map((w, i) => (
            <button
              key={i}
              onClick={() => setActive(i)}
              style={{
                textAlign: 'left',
                padding: '10px 14px',
                background: active === i ? 'rgba(88,166,255,0.1)' : 'var(--bg-card)',
                border: `1px solid ${active === i ? 'var(--accent-blue)' : 'var(--border)'}`,
                borderRadius: 'var(--radius)',
                cursor: 'pointer',
                transition: 'all 0.2s',
                fontFamily: 'inherit'
              }}
            >
              <div style={{ color: active === i ? 'var(--accent-blue)' : 'var(--text-primary)', fontWeight: 700, fontSize: 13 }}>{w.title}</div>
              <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginTop: 2 }}>{w.file}</div>
            </button>
          ))}
        </div>

        {/* Details */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div>
            <div style={{ fontSize: 18, fontWeight: 800, marginBottom: 6, color: 'var(--accent-blue)' }}>{current.title}</div>
            <div style={{ display: 'flex', gap: 6 }}>
              {current.tags.map(t => <span key={t} className="tag tag-blue" style={{ fontSize: 10 }}>{t}</span>)}
            </div>
          </div>

          <div style={{ background: 'var(--bg-secondary)', padding: 12, borderRadius: 'var(--radius)', border: '1px solid var(--border)' }}>
            <div style={{ fontSize: 11, fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 6 }}>The Simple Explanation</div>
            <p style={{ fontSize: 14, lineHeight: 1.6, margin: 0, color: 'var(--text-primary)' }}>{current.desc}</p>
          </div>

          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 11, fontWeight: 800, color: 'var(--accent-green)', textTransform: 'uppercase', marginBottom: 8 }}>How to Live Demo</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {current.demo.split('. ').map((step, i) => (
                <div key={i} style={{ display: 'flex', gap: 10, fontSize: 13, color: 'var(--text-secondary)' }}>
                  <span style={{ color: 'var(--accent-green)', fontWeight: 800 }}>{i + 1}</span>
                  <span>{step}</span>
                </div>
              ))}
            </div>
          </div>

          <div style={{ fontSize: 11, color: 'var(--text-muted)', borderTop: '1px solid var(--border)', paddingTop: 10 }}>
            💡 Tip: Have the GitHub "Actions" tab open in another browser tab to show the status in real-time.
          </div>
        </div>
      </div>
    </div>
  )
}
