import { useState } from 'react'

const workflows = [
  {
    file: 'docker-build-push.yml',
    title: '🐳 Docker Build & Push',
    desc: 'Takes your code, puts it in a container, and sends it to GitHub & Docker Hub.',
    concepts: ['Multi-platform (arm64/amd64)', 'Layer Caching', 'SBOM Identity', 'Vulnerability Scanning'],
    flow: ['Build', 'Scan', 'Attest', 'Push'],
    demo: '1. Create a tag starting with "v" (e.g. v1.0.0). 2. Watch it build for both Intel and Mac chips. 3. Check your GitHub Packages page for the result.',
    tags: ['Multi-arch', 'Security']
  },
  {
    file: 'ci-advanced.yml',
    title: '🧪 Advanced CI',
    desc: 'Comprehensive testing and infrastructure connection demo.',
    concepts: ['Dynamic Matrix Configuration', 'OIDC (OpenID Connect)', 'Identity Federation', 'Concurrency Control'],
    flow: ['Matrix Init', 'Parallel Tests', 'AWS Auth', 'Size Check'],
    demo: '1. Go to Actions → "Advanced CI Pipeline". 2. Click "Run workflow". 3. Observe the "Matrix" splitting the work into multiple parallel jobs.',
    tags: ['OIDC', 'Advanced']
  },
  {
    file: 'release-automation.yml',
    title: '🚀 Auto-Release',
    desc: 'Fully automated versioning and distribution platform.',
    concepts: ['Conventional Commits', 'Semantic Versioning', 'Automatic Changelog', 'NPM/GitHub Release'],
    flow: ['Semantic Check', 'Tagging', 'Asset Prep', 'Publish'],
    demo: '1. Push a commit starting with "feat:" or "fix:". 2. Observe as a new GitHub Release is created automatically with professional notes.',
    tags: ['Semantic', 'Automation']
  },
  {
    file: 'pr-automation.yml',
    title: '🤖 PR Assistant',
    desc: 'Automating the code review lifecycle and team standards.',
    concepts: ['PR Metadata Extraction', 'Dynamic Labeling', 'Commenting API', 'Branch Protection'],
    flow: ['Event Listen', 'Size Calc', 'Auto Label', 'Review Post'],
    demo: '1. Open a new Pull Request. 2. Notice the "Size" label (XS/S/M/L) and the automated checklist comment that appears.',
    tags: ['Ops', 'Team']
  },
  {
    file: 'security-scan.yml',
    title: '🛡️ Security Guard',
    desc: 'Proactive defense against vulnerabilities and secret leaks.',
    concepts: ['SAST (CodeQL)', 'DAST (OWASP ZAP)', 'Secret Detection', 'SARIF Reporting'],
    flow: ['Gitleaks', 'CodeQL Init', 'Analysis', 'Security Tab'],
    demo: '1. Go to Github → Security → Code scanning. 2. See the detailed vulnerability report generated by this workflow.',
    tags: ['SAST', 'DAST']
  },
  {
    file: 'scheduled-tasks.yml',
    title: '⏰ Scheduled Jobs',
    desc: 'Maintenance and reporting running on a cron schedule.',
    concepts: ['Cron Schedules', 'Issue Automation', 'System Health Checks', 'Artifact Cleanup'],
    flow: ['Trigger', 'Fetch Stale', 'Auto Close', 'Health Ping'],
    demo: '1. Run this manually via "workflow_dispatch". 2. Go to Issues and see if a new "Weekly Report" was posted by the robot.',
    tags: ['Cron', 'Maintenance']
  }
]

export default function SlideYAMLGuide() {
  const [active, setActive] = useState(0)
  const current = workflows[active]

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column', gap: 12 }}>
      <div>
        <div className="tag tag-green fade-up delay-1" style={{ marginBottom: 8 }}>04 — Presenter's Guide</div>
        <h2 className="section-title fade-up delay-2">Workflow Demos: How to Present</h2>
        <p className="section-subtitle fade-up delay-3">Simple descriptions and instructions for live testing the YAML files</p>
      </div>

      <div className="grid-2 fade-up delay-2" style={{ gap: 16, flex: 1, overflow: 'hidden' }}>
        {/* List */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 6, overflowY: 'auto' }}>
          {workflows.map((w, i) => (
            <button
              key={i}
              onClick={() => setActive(i)}
              style={{
                textAlign: 'left',
                padding: '10px 14px',
                background: active === i ? 'rgba(88,166,255,0.1)' : 'var(--bg-card)',
                border: `1px solid ${active === i ? 'var(--accent-blue)' : 'var(--border)'}`,
                borderRadius: 'var(--radius)',
                cursor: 'pointer',
                transition: 'all 0.2s',
                fontFamily: 'inherit'
              }}
            >
              <div style={{ color: active === i ? 'var(--accent-blue)' : 'var(--text-primary)', fontWeight: 700, fontSize: 13 }}>{w.title}</div>
              <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginTop: 2 }}>{w.file}</div>
            </button>
          ))}
        </div>

        {/* Details */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div>
            <div style={{ fontSize: 18, fontWeight: 800, marginBottom: 6, color: 'var(--accent-blue)' }}>{current.title}</div>
            <div style={{ display: 'flex', gap: 6 }}>
              {current.tags.map(t => <span key={t} className="tag tag-blue" style={{ fontSize: 10 }}>{t}</span>)}
            </div>
          </div>

          <div style={{ background: 'var(--bg-card)', padding: 12, borderRadius: 'var(--radius)', border: '1px dashed var(--border)' }}>
            <div style={{ fontSize: 11, fontWeight: 800, color: 'var(--accent-blue)', textTransform: 'uppercase', marginBottom: 10, display: 'flex', alignItems: 'center', gap: 6 }}>
              Pipeline Flow
              <div style={{ height: 1, flex: 1, background: 'var(--border)' }}></div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', position: 'relative' }}>
              {current.flow.map((step, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center', flex: 1 }}>
                  <div style={{ 
                    width: 24, 
                    height: 24, 
                    borderRadius: '50%', 
                    background: 'var(--bg-secondary)', 
                    border: '1px solid var(--accent-blue)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: 10,
                    fontWeight: 800,
                    color: 'var(--accent-blue)',
                    zIndex: 2
                  }}>
                    {i + 1}
                  </div>
                  <div style={{ fontSize: 9, fontWeight: 700, marginLeft: 6, color: 'var(--text-secondary)' }}>{step}</div>
                  {i < current.flow.length - 1 && (
                    <div style={{ flex: 1, height: 1, background: 'var(--border)', margin: '0 8px' }}></div>
                  )}
                </div>
              ))}
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
            <div style={{ background: 'var(--bg-secondary)', padding: 12, borderRadius: 'var(--radius)', border: '1px solid var(--border)' }}>
              <div style={{ fontSize: 11, fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 6 }}>Key Concepts</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                {current.concepts.map(c => (
                  <div key={c} style={{ fontSize: 11, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: 6 }}>
                    <div style={{ width: 4, height: 4, borderRadius: '50%', background: 'var(--accent-blue)' }}></div>
                    {c}
                  </div>
                ))}
              </div>
            </div>

            <div style={{ background: 'rgba(52,211,153,0.05)', padding: 12, borderRadius: 'var(--radius)', border: '1px solid rgba(52,211,153,0.2)' }}>
              <div style={{ fontSize: 11, fontWeight: 800, color: 'var(--accent-green)', textTransform: 'uppercase', marginBottom: 8 }}>Live Demo Steps</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                {current.demo.split('. ').map((step, i) => (
                  <div key={i} style={{ display: 'flex', gap: 8, fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.4 }}>
                    <span style={{ color: 'var(--accent-green)', fontWeight: 800 }}>{i + 1}</span>
                    <span>{step}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div style={{ fontSize: 11, color: 'var(--text-muted)', borderTop: '1px solid var(--border)', paddingTop: 10, textAlign: 'center' }}>
            💡 Tip: Open GitHub Actions tab in real-time to show the pipeline execution status.
          </div>
        </div>
      </div>
    </div>
  )
}
